### PR TITLE
Update 03 - RClone - UnionFS Sync & Move

### PR DESCRIPTION
**Pull request by Deiteq**
Added option to create and use a RClone Encrypted mount point, but have only managed to test it using 'plexdrive5' and not 'plexdrive4' as it never seems to work for me.

### CODE REVIEW

**Comment by Admin9705** [comment]
@Deiteq , can you update now.  I fixed the unionfs issue.  Seeing your using the traditional method.  those this make sense?  had to remove (cow) from the unionfs service and it fixed it.

**Comment by Deiteq** [comment]
Hey, sorry for the delay, been busy.
I have delete `cow` from the unionfs service but I still get the following output:-

`● unionfs.service - UnionFS Daemon
   Loaded: loaded (/etc/systemd/system/unionfs.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Sun 2017-10-01 12:24:20 CEST; 2min 40s ago
  Process: 5850 ExecStart=/usr/bin/unionfs -o allow_other,nonempty /mnt/rclone-move=RW:/mnt/rclone=RO /mnt/rclone-union (code=exited, status=0/SUCCESS)
 Main PID: 5850 (code=exited, status=0/SUCCESS)
    Tasks: 16
   Memory: 3.6M
      CPU: 29ms
   CGroup: /system.slice/unionfs.service
           ├─5526 /usr/bin/unionfs -o allow_other,nonempty /mnt/rclone-move=RW:/mnt/rclone=RO /mnt/rclone-union
           ├─5722 /usr/bin/unionfs -o allow_other,nonempty /mnt/rclone-move=RW:/mnt/rclone=RO /mnt/rclone-union
           ├─5757 /usr/bin/unionfs -o allow_other,nonempty /mnt/rclone-move=RW:/mnt/rclone=RO /mnt/rclone-union
           ├─5827 /usr/bin/unionfs -o allow_other,nonempty /mnt/rclone-move=RW:/mnt/rclone=RO /mnt/rclone-union
           └─5853 /usr/bin/unionfs -o allow_other,nonempty /mnt/rclone-move=RW:/mnt/rclone=RO /mnt/rclone-union

Oct 01 12:24:20 v22017084877152626 systemd[1]: unionfs.service: Service hold-off time over, scheduling restart.
Oct 01 12:24:20 v22017084877152626 systemd[1]: Stopped UnionFS Daemon.
Oct 01 12:24:20 v22017084877152626 systemd[1]: unionfs.service: Start request repeated too quickly.
Oct 01 12:24:20 v22017084877152626 systemd[1]: Failed to start UnionFS Daemon.`

Doesn't matter as I think it's working because I am able to see both my google drive files and the local ones together within `/mnt/rclone-union`.

What I don't understand are the conflicts with this branch, for some reason there are 3 when there should only be 1, oh well, I will keep my edits and just delete the cron job part.

**Comment by Alasano** [comment]
Hey @Deiteq and @Admin9705 - This happened to me too but I resolved it by setting the option "RemainAfterExit=yes" in the [Service] node of the unionfs service definition

sudo nano /etc/systemd/system/unionfs.service 

Think there may be better a solution by changing the type of the service but this works well and it stops it from constantly trying to restart the UnionFS daemon as it knows that it's active even though it can't detect it correctly it seems.

**Comment by Admin9705** [comment]
Makes sense, I’ll make the change tomorrow and over look the request. Was
busy with another adobe project ;) thanks for your help and advise!

**Comment by Deiteq** [comment]
Hey @Alasano 
This fixed the issue for me!
Thanks dude!

**Comment by Admin9705** [comment]
@Alasano making the fix now.  Thanks for helping us so much!

**Comment by Admin9705** [comment]
@Deiteq, I'll make another file seperate, original will be changed to unenrcypted version and yours will be called encrypted.  I'll credit you incase :D

**Pull request closed without merging**
